### ISSUE TITLE
issues running the demo

### ISSUE THREAD

**Issue by iferencik** [carbonplan/maps#36] opened 2021-12-06 22:12 UTC
Hello @freeman-lab and @katamartin 

I'd like to thank you for creating  this interesting library. I am trying to run your demo app and got encountered following

Error: [useColorMode] requires the ColorModeProvider component

I have very little react/nextjs knowledge but as far as I understood it seems to be a problem to theme-ui not exporting any  types or something similar.

Do you have any suggestion how i could fix this?

I am planning to create a prototype and publish electricity access data from HREA (http://www-personal.umich.edu/~brianmin/HREA/)
with your lib.

For this I have created a python script to convert the Gtif into  multiscale zarr  and I would like to know if:

1. is it possible to publish the data from local folder instead of hosting it on AWS/Azure? 

2. could such an application be working hosted outside a server (Azure blob for example?). I read nextjs can be used to serve web apps from a CDN.

Thank you in advance and again very very interesting work.

**Comment by katamartin** [comment] 2021-12-07 01:01
Hi @iferencik! Thanks for reaching out and for your kind words.

I just tried to reproduce your error and was unable to when freshly cloning the repo, running `cd demo`, `npm install` and `npm run dev`. This looks like an error we've encountered in our ecosystem in the past when there were mismatching versions of `theme-ui` between a project and one of its dependencies. This was a bug that was fixed in `@carbonplan/colormaps` version `2.0.2`, which should be getting picked up on fresh install. To debug further, you could try running `rm -rf node_modules` from within `demo` and reinstalling. 

Also for what it's worth, https://github.com/carbonplan/simple-map-demo may be a more helpful template to use for starting a new Next.js project that uses this library.

As for your other questions:
1. You can absolutely test with local files by starting a server (e.g. using `python -m http.server`) in the folder with your data.
2. Yeah, you should have a lot of flexibility for hosting Next.js static sites, including using services like Azure (it looks like there are actually existing [Microsoft docs](https://docs.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs) for this!).

**Comment by iferencik** [comment] 2021-12-07 16:46
Hello @katamartin and thanks you for you timely reply.

> Hi @iferencik! Thanks for reaching out and for your kind words.
> 
> I just tried to reproduce your error and was unable to when freshly cloning the repo, running `cd demo`, `npm install` and `npm run dev`. This looks like an error we've encountered in our ecosystem in the past when there were mismatching versions of `theme-ui` between a project and one of its dependencies. This was a bug that was fixed in `@carbonplan/colormaps` version `2.0.2`, which should be getting picked up on fresh install. To debug further, you could try running `rm -rf node_modules` from within `demo` and reinstalling.
> 
> Also for what it's worth, https://github.com/carbonplan/simple-map-demo may be a more helpful template to use for starting a new Next.js project that uses this library.

good point, I will try this simpler demo for a start

> 
> As for your other questions:
> 
> 1. You can absolutely test with local files by starting a server (e.g. using `python -m http.server`) in the folder with your data.

I have tried this and it works. I wanted to know if it is possible to read the files from local disk (without a server).
I guess this would depend on whether zarr-js (i believe this should be possible) can do it and whether maps lib is designed/allowed to use this approach.



> 2. Yeah, you should have a lot of flexibility for hosting Next.js static sites, including using services like Azure (it looks like there are actually existing [Microsoft docs](https://docs.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs) for this!).


thanks for pointing me to the MS Azure docs.

**Comment by katamartin** [comment] 2021-12-07 17:14
Hi @iferencik!

> I wanted to know if it is possible to read the files from local disk (without a server).

Ah, I see. This is not possible, principally because `maps` is not designed to use `zarr-js` with `fs.readFile`. I'm not sure that this is something we would want to support because of the performance implications of bundling potentially large Zarr stores alongside client applications.

Thanks again for reaching out and feel free to reopen if you find any more sticking points with the library.

**Closed by katamartin** 2021-12-07 17:14 UTC
